# Generated by Django 5.2.6 on 2025-10-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('milk', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('mood', models.CharField(default='happy', max_length=20)),
            ],
        ),
    ]
