# Generated by Django 5.2.6 on 2025-10-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='level',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='milk',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='mood',
        ),
        migrations.AddField(
            model_name='cat',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
