# Generated by Django 5.2.6 on 2025-10-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_cat_level_remove_cat_milk_remove_cat_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cat',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cat',
            name='milk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
