# Generated by Django 5.2.6 on 2025-10-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_cat_clicks_cat_level_cat_milk_alter_cat_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='clicks',
            new_name='score',
        ),
    ]
