# Generated by Django 5.2.6 on 2025-10-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_clicks_cat_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='score',
        ),
        migrations.AddField(
            model_name='cat',
            name='mood',
            field=models.CharField(default='happy', max_length=20),
        ),
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cat_photos/'),
        ),
    ]
