# Generated by Django 5.2.6 on 2025-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_cat_image_url_remove_cat_score_cat_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='level',
        ),
        migrations.AlterField(
            model_name='cat',
            name='mood',
            field=models.CharField(choices=[('happy', 'Счастливый'), ('grumpy', 'Сердитый'), ('sleepy', 'Сонный')], default='happy', max_length=20),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cats/'),
        ),
    ]
