# Generated by Django 5.2.6 on 2025-10-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_cat_level_alter_cat_mood_alter_cat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
